spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/blue_velvet_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/blue_velvet_events}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy-secret}
            scope:
              - openid
              - profile
              - email

jwt:
  secret: ${JWT_SECRET:TXkgc3VwZXIgc2VjcmV0IGtleSBwYXJhIGVsIHJlc3RhdXJhbnRl} # Mínimo 44 caracteres Base64
  expiration-ms: ${JWT_EXPIRATION:3600000} # 1 hora
  expiration: ${jwt.expiration-ms}
